### ISSUE TITLE
Resolve does not check for valid optional arguments

### ISSUE THREAD

**Issue by CrashBurnRepeat** [ztangent/FOL.jl#10]
Following up from #9, `resolve` does not actively check to make sure optional arguments are valid, instead checking for specific options (such as `:dfs` for `search`) and otherwise using the default option. This can lead to silent "failures" where the user may not know `resolve` is using different settings than the user intended.

**Comment by ztangent** [comment]
Belatedly realizing this was fixed in b6a5afd2bb27!
