### ISSUE TITLE
Engine does not run through all available variants

### ISSUE THREAD

**Issue by pddshk** [ztangent/FOL.jl#13]
I tried to implement simple zebra puzzle. After several hours of struggling through I decided to implement simple check test: generate all permutations on 4 elements

```julia
clauses = @julog [
     tuples(T) <<= 
        eq(T, [_,_,_,_]) &
        subset([1,2,3,4], T),
        
    eq(A,A)',
    member(X, [X | Y])',
    member(X, [Y | YS]) <<= member(X, YS),
    subset([],_)',
    subset([X | XS], L) <<= member(X,L) & subset(XS,L)
]
goals = @julog [tuples(T)]
resolve(goals,clauses)[2]
```

However the output was

```
8-element Array{Any,1}:
 {T => [1, 2, 3, 4]}
 {T => [1, 2, 4, 3]}
 {T => [1, 3, 2, 4]}
 {T => [1, 4, 2, 3]}
 {T => [2, 1, 3, 4]}
 {T => [2, 1, 4, 3]}
 {T => [3, 1, 2, 4]}
 {T => [4, 1, 2, 3]}
```
Instead of all 24 permutations
I wrote very similar code on Prolog to compare results:

```prolog
tuples(T) :-
    T = [_,_,_,_],
    subset([1,2,3,4],T).

subset([],_).

subset([X | XS], L) :-
    member(X,L),
    subset(XS,L).

?- tuples(T)
```
And got right result

```
T = [1, 2, 3, 4]
T = [1, 2, 4, 3]
T = [1, 3, 2, 4]
T = [1, 4, 2, 3]
T = [1, 3, 4, 2]
T = [1, 4, 3, 2]
T = [2, 1, 3, 4]
T = [2, 1, 4, 3]
T = [3, 1, 2, 4]
T = [4, 1, 2, 3]
T = [3, 1, 4, 2]
T = [4, 1, 3, 2]
T = [2, 3, 1, 4]
T = [2, 4, 1, 3]
T = [3, 2, 1, 4]
T = [4, 2, 1, 3]
T = [3, 4, 1, 2]
T = [4, 3, 1, 2]
T = [2, 3, 4, 1]
T = [2, 4, 3, 1]
T = [3, 2, 4, 1]
T = [4, 2, 3, 1]
T = [3, 4, 2, 1]
T = [4, 3, 2, 1]
```

This shows that Julog engine does not run through all available variants

**Comment by ztangent** [comment]
Thanks for catching this bug! Really strange that this is happening, I'll take a deeper look when I have time.

In the meantime, the zebra puzzle is actually one of the benchmarks I've been using for performance testing: https://github.com/ztangent/Julog.jl/blob/master/benchmarks/zebra.jl

Hope that helps as a reference!

**Comment by ztangent** [comment]
Just did some experimentation, and it looks like if you have both of the clauses:
```julia
    subset([X | XS], L) <<= member(X,L) & subset(XS,L),
    subset([X | XS], L) <<= subset(XS,L) & member(X, L)
```
you get the expected 24 permutations. I'm not sure why the order is having such an important effect though, will require some thought.

**Comment by ztangent** [comment]
Okay, fixed in the most recent commits! Turns out I wasn't creating fresh variable names prior to unification, which was causing problems with variable binding. Will register a new version on the Julia registry soon.

And thanks for contributing this test case, I've included it [here](https://github.com/ztangent/Julog.jl/blob/master/test/permutations.jl)! :)
