### ISSUE TITLE
Error: LoadError: $Expr(:incomplete, "...") & How to extend `builtins`?

### ISSUE THREAD

**Issue by AIxer** [ztangent/FOL.jl#15]
Hi, I am working on a `Reasoning System`,  it has rules written in `SWI-Prolog`: [nal.pl](https://cis.temple.edu/~pwang/Implementation/NAL/nal.pl).
I want to use it in `Julia`, but there're some predicates like `member`、`nonvar` and `subtract` are not in `Julog`'s builtins.

When I use `@prolog` to parse [nal.pl](https://cis.temple.edu/~pwang/Implementation/NAL/nal.pl):
```julia
using Julog

rules = @prolog """
     prolog rules in nal.pl
"""
```
I got an `Error`:
```juliarepl
Expr
  head: Symbol incomplete
  args: Array{Any}((1,))
    1: String "incomplete: premature end of input"
ERROR: LoadError: syntax error in Julog term at $(Expr(:incomplete, "incomplete: premature end of input"))
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] parse_term(expr::Expr, esc::typeof(esc))
   @ Julog C:\Users\Axier\.julia\packages\Julog\V6gVn\src\parse.jl:38
 [3] parse_julog(expr::Expr, esc::Function)
   @ Julog C:\Users\Axier\.julia\packages\Julog\V6gVn\src\parse.jl:111
in expression starting at D:\codes\Junars\src\rules\julogrules.jl:3
in expression starting at D:\codes\Junars\src\rules\julogrules.jl:3
```
How can I make these rules work in `Julog`?

**Comment by ztangent** [comment]
So the parsing provided by `@prolog` isn't perfect, and without more careful debugging, it's hard to know why the parser isn't working here -- the one thing I can think of is that I don't think Julog.jl supports comments in Prolog right now, so maybe try removing those?

As for adding builtins, I would like to have a more efficient way of doing this, but currently I think your best bet is to add clauses for predicates like `member` and `subtract` to the list of clauses you provide to `resolve`, and to implement `nonvar` using a custom function.  You can see [this example](https://github.com/ztangent/Julog.jl/blob/master/test/lists.jl) for Julog definitions of list-related predicates like `member`. Hope this helps!

**Comment by AIxer** [comment]
Thanks!
I think the problem is here  `C is (W / W + K)`:
```juliarepl
julia> f = @prolog """
       u_w2c(W, C) :-
           K = 1, C is (W / (W + K)), !.
       """
Expr
  head: Symbol incomplete
  args: Array{Any}((1,))
    1: String "incomplete: premature end of input"
ERROR: LoadError: syntax error in Julog term at $(Expr(:incomplete, "incomplete: premature end of input"))
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] parse_term(expr::Expr, esc::typeof(esc))
   @ Julog C:\Users\Axier\.julia\packages\Julog\V6gVn\src\parse.jl:38
 [3] parse_julog(expr::Expr, esc::Function)
   @ Julog C:\Users\Axier\.julia\packages\Julog\V6gVn\src\parse.jl:111
in expression starting at REPL[2]:1
```
Well,  I have to rewrite it, but I'm not good at `Prolog`, may be I need to learn about it. or give up this way~ 😄

**Comment by AIxer** [comment]
I‘v done some work, translated all the rules in `nal.pl` into `Julog` style. 
Happily, it partially works and no `Error` reported, but there are still some problems. 
well, one of the problem is `L1 =.. L2`, `=..` is `SWI-Prolog` 's built-in, I wrote a custom function `univ`, it can translate `Term` into a `Julia Vector` of `Julog Term`, obviously, it's not what I need.
So, how to implement it?
I hope to get your help. Much appreciated.

**Comment by AIxer** [comment]
a problem like above, I can't figure out how to implement `nonvar` with `custom functions`:
```julia
funcs = Dict()
funcs[:nonvar] = x -> !isa(x, Var)
funcs[:ground] = x -> is_ground(x)
```
```juliarepl
julia> goal = @julog ground(atomic(x))
ground(atomic(x))

julia> resolve(goal, Clause[]; funcs)
(false, Any[])
```
or
```julia
funcs = Dict()
funcs[:nonvar] = x -> !isa(@julog(x), Var)
funcs[:ground] = x -> is_ground(@julog(x))
```
```juliarepl
julia> goal = @julog ground(atomic(x))
ground(atomic(x))

julia> resolve(goal, Clause[]; funcs)
(false, Any[])
```
Both are not working. 😭
Any instructions? 🙏  Thanks a lot! @ztangent

**Comment by AIxer** [comment]
Well, I think some functions like `ground`, `nonvar` and `atom` may cannot be supported currently. Because of [Julog's code here.](https://github.com/ztangent/Julog.jl/blob/master/src/main.jl#:~:text=if%20func%20!%3D%3D%20nothing,a%20in%20args)

**Comment by ztangent** [comment]
I think you're right! Oof. Maybe you fork Julog and modify the `handle_builtins!` function so that it knows how to deal with `atomic` and `nonvar`? If you make a PR I'd be happy to review it!

**Comment by AIxer** [comment]
Yes, I've forked just now, but only added `ground`, `nonvar` and `atom` for my project purpose. Then is `Univ`, but I have no idea now.

**Comment by ztangent** [comment]
Yeah it seems like Univ might take more work... Julog does have some convenience functions to convert Julia lists into Julog lists, and vice versa, which I think might help! You probably want to handle it is a builtin, and make sure you handle both the case where LHS and RHS are variables.

**Comment by ztangent** [comment]
This is probably the function you want to use:

https://github.com/ztangent/Julog.jl/blob/01367bc8aa0a84304ff0b7c553223f274cf2ebbd/src/utils.jl#L130-L132

**Comment by AIxer** [comment]
Thanks! Ordinary Prolog implementation will use `functor` and `arg` to achieve `Univ`, but I think use julia function directly maybe more efficient, make it just act like `Univ` 😃

**Comment by AIxer** [comment]
> You probably want to handle it is a builtin, and make sure you handle both the case where LHS and RHS are variables.


`to_term_list` then `unifies` ?
emmm, actually, I haven't fully understood Julog's operational mechanism. 😄
